---
name: create self hosted runner
description: create self hosted runner

runs:
  using: composite
  steps:
    - name: run hosted_runner deployment
      shell: bash
      run: |
        cd ${{github.action_path}}/../../cluster/gh-action-runner/
        source utils.sh

        gh_action_template_create

        #create a runner VM from the template
        gh_action_runner_create  
