---
kind: Secret
apiVersion: v1
metadata:
  name: ovirt-provider-secret
  namespace: konveyor-forklift
  labels:
    createdForResource: ovirt-provider
    createdForResourceType: providers
data:
  # insecureSkipVerify: 1
  # insecureSkipVerify: MQ==
  cacert: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0ekNDQXArZ0F3SUJBZ0lVZUhoWExpSkpwYUlsZDR0WTdJNWY4bTdSanR3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FqRUxNQWtHQTFVRUJoTUNXRmd4RlRBVEJnTlZCQWNNREVSbFptRjFiSFFnUTJsMGVURWNNQm9HQTFVRQpDZ3dUUkdWbVlYVnNkQ0JEYjIxd1lXNTVJRXgwWkRBZUZ3MHlNakV4TURFd09UUTVORE5hRncwek1qRXdNamt3Ck9UUTVORE5hTUlHQ01Rc3dDUVlEVlFRR0V3SllXREVWTUJNR0ExVUVCd3dNUkdWbVlYVnNkQ0JEYVhSNU1Sd3cKR2dZRFZRUUtEQk5FWldaaGRXeDBJRU52YlhCaGJua2dUSFJrTVQ0d1BBWURWUVFERERWbVlXdGxiM1pwY25RdQphMjl1ZG1WNWIzSXRabTl5YTJ4cFpuUXNhVzFoWjJWcGJ5NXJiMjUyWlhsdmNpMW1iM0pyYkdsbWREQ0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMZmZ4VlBOK0xpbjIxd0RiUG5GYzF3ZWliZkQKbUhxY1hmeklNSGFhSHZWM01BM0lYZTVxM2ttSmx0MXpjMWRzNHlkb2FZUmNKZU5wdUE3RnI0UGRBVEhWcXhaQgpqQzltK3dCL0ExNkJnVDY5VlBtbkRXdXpta2tuK05NOEpkQlJ2K3hPRkpzMVA5bmRNRnRIZ1NLMW8vK3NHcEdqCmFWdXVaYk9kNGRyRzhiaFlXS1doeEhURGtGakdlOUM4Mkc2WFkxUWsyZ0IyZjVFQTMwdW8vc1NMWXVyNjlIaUsKSFNzN3IrUkFhRVM3d2xNN056NEhyZjRYQUkycWNkSE5JMVQ1WnBEWGtaTnBnQzZsLzltNUZJVWplVnpIcWYwZwpNekNJUFRCd2pwNHpKT01JUTIxRDRjWG0yWmkvbmxyTTYwSWZBZDdEWlgyV3FCQ2FVakVMREhGVEZVRUNBd0VBCkFhTmtNR0l3UVFZRFZSMFJCRG93T0lJYlptRnJaVzkyYVhKMExtdHZiblpsZVc5eUxXWnZjbXRzYVdaMGdobHAKYldGblpXbHZMbXR2Ym5abGVXOXlMV1p2Y210c2FXWjBNQjBHQTFVZERnUVdCQlNvU29QS1NBbzNVMGJEby8wVQpoZ0FjZVk0WmdUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFCNEI3RENpcHNDeFJZcTh0MCthMUlVWUNjV2JzCkFJNDBHaFJnMms2L3A0Z1AyV1UvdjZUUnBRM0h1eFkyVHR5M0lkZXpNQlp6ZVcyTmdRQnh0L0VvOWNmV1RzLzUKeVg3a0lDelF2ck9hYlRnRjg0RWNDZVJsUCtJdDl4amZXV0c0YWRFeXYwWEVUallVRzg1ckJXN3VkOG42ZE9NWQpjT2dkT2NKMVZ2cURBZkFGMXVEWU9JcEVkcUVTcm5xVHhqK3Fld2xCcEJ2Mlk4bThuYStBTDlTeTZyZGtWOTBlCnhLZmlKRy9PUU5KRXpncEsxWFVTaC9FZzNnRW5ycHVBK2pXeFNoT0wwekpGYk1RREEwb3h2NnduQnhMSVpYcFEKOGREc2lpcEdONkhEWlVwenhIR0ZERFBCN3h0Q0ZHanlMQlhDTGVnaCszMVhuWjd3NkF6WTNtSUJZdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  password: MTIzNDU2
  user: YWRtaW5AaW50ZXJuYWw=
type: Opaque

---
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
metadata:
  name: ovirt-provider
  namespace: konveyor-forklift
spec:
  secret:
    name: ovirt-provider-secret
    namespace: konveyor-forklift
  type: ovirt
  url: https://fakeovirt.konveyor-forklift:12346/ovirt-engine/api
