name: Forklift_Build_KinD
on:
  workflow_dispatch:
      name:
        description: 'Build forklift from source and deploy it on KinD'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USE_BAZEL_VERSION: 5.4.0
    steps:
      - name: Check out forkliftci repository
        uses: actions/checkout@v3

      - name: Add cwd to path for kubectl.
        run: echo `pwd` >> $GITHUB_PATH
      - name: build and setup everything
        uses: ./ci/build-and-setup/
        with:
          provider_name: all
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: kubectl version

      - run: kubectl wait deployment -n konveyor-forklift forklift-controller --for condition=Available=True --timeout=180s

      - run: kubectl describe nodes
    
      - run: kubectl get pods -n konveyor-forklift

      - run: kubectl get providers -n konveyor-forklift -o yaml

      - run: kubectl get migrations -n konveyor-forklift -o yaml

      - run: kubectl get plans -n konveyor-forklift -o yaml

      - run: echo "CLUSTER=`kind get kubeconfig | grep server | cut -d ' ' -f6`" >> $GITHUB_ENV
      - run: echo "TOKEN=`kubectl get secrets -n kube-system -o jsonpath='{.items[0].data.token-id}' | base64 -d`.`kubectl get secrets -n kube-system -o jsonpath='{.items[0].data.token-secret}' | base64 -d`" >> $GITHUB_ENV 

      - name: save logs
        if: ${{ always() }}
        uses: ./ci/save-artifacts/
        with:
          source_provider: all
              
      - name: Test call to Forklift
        run: |
          curl -k "$CLUSTER/apis/forklift.konveyor.io/v1beta1/namespaces/konveyor-forklift/providers" --header "Authorization: Bearer $TOKEN"
